use anchor_lang::prelude::*;

/// On-chain referral code account
/// PDA seeds: [b"referral_code", code_bytes]
#[account]
#[derive(Default)]
pub struct ReferralCode {
    /// The wallet that owns this referral code
    pub owner: Pubkey,

    /// The referral code (8 bytes, uppercase alphanumeric)
    pub code: [u8; 8],

    /// Discount percent for referred users (basis points, 1000 = 10%)
    pub discount_bps: u16,

    /// Reward percent for referrer (basis points, 2000 = 20%)
    pub reward_bps: u16,

    /// Total number of users referred
    pub total_referred: u32,

    /// Total trading volume from referrals (6 decimals)
    pub total_volume: u64,

    /// Total fees generated by referrals (6 decimals)
    pub total_fees_generated: u64,

    /// Total rewards earned (6 decimals)
    pub total_rewards_earned: u64,

    /// Pending rewards available to claim (6 decimals)
    pub pending_rewards: u64,

    /// Timestamp when the code was created
    pub created_at: i64,

    /// Whether this code is active
    pub is_active: bool,

    /// PDA bump
    pub bump: u8,
}

impl ReferralCode {
    pub const LEN: usize = 8 +  // discriminator
        32 +  // owner
        8 +   // code
        2 +   // discount_bps
        2 +   // reward_bps
        4 +   // total_referred
        8 +   // total_volume
        8 +   // total_fees_generated
        8 +   // total_rewards_earned
        8 +   // pending_rewards
        8 +   // created_at
        1 +   // is_active
        1 +   // bump
        32;   // padding

    pub const DEFAULT_DISCOUNT_BPS: u16 = 1000;  // 10%
    pub const DEFAULT_REWARD_BPS: u16 = 2000;    // 20%
    pub const MAX_DISCOUNT_BPS: u16 = 5000;      // 50% max discount
    pub const MAX_REWARD_BPS: u16 = 5000;        // 50% max reward

    /// Convert code bytes to string
    pub fn code_str(&self) -> String {
        String::from_utf8_lossy(&self.code)
            .trim_end_matches('\0')
            .to_string()
    }

    /// Create code bytes from string (uppercase, max 8 chars)
    pub fn code_from_str(s: &str) -> [u8; 8] {
        let mut bytes = [0u8; 8];
        let upper = s.to_uppercase();
        let src = upper.as_bytes();
        let len = src.len().min(8);
        bytes[..len].copy_from_slice(&src[..len]);
        bytes
    }

    /// Validate code format (alphanumeric only)
    pub fn is_valid_code(code: &[u8; 8]) -> bool {
        for &byte in code.iter() {
            if byte == 0 {
                break; // End of string
            }
            // Must be A-Z or 0-9
            if !((byte >= b'A' && byte <= b'Z') || (byte >= b'0' && byte <= b'9')) {
                return false;
            }
        }
        // Must have at least 4 characters
        code[0] != 0 && code[1] != 0 && code[2] != 0 && code[3] != 0
    }
}

/// User's referral relationship - tracks which code a user applied
/// PDA seeds: [b"user_referral", user_pubkey]
#[account]
#[derive(Default)]
pub struct UserReferral {
    /// The user who applied a referral code
    pub user: Pubkey,

    /// The referral code they're using
    pub referral_code: Pubkey,

    /// The referrer's wallet (for quick lookup)
    pub referrer: Pubkey,

    /// Discount this user receives (cached from referral code)
    pub discount_bps: u16,

    /// Total volume traded by this user
    pub total_volume: u64,

    /// Total fees paid by this user
    pub total_fees_paid: u64,

    /// Total fees sent to referrer
    pub total_referrer_rewards: u64,

    /// When the referral was applied
    pub applied_at: i64,

    /// PDA bump
    pub bump: u8,
}

impl UserReferral {
    pub const LEN: usize = 8 +  // discriminator
        32 +  // user
        32 +  // referral_code
        32 +  // referrer
        2 +   // discount_bps
        8 +   // total_volume
        8 +   // total_fees_paid
        8 +   // total_referrer_rewards
        8 +   // applied_at
        1 +   // bump
        16;   // padding
}
